name: devtools_repo
description: A repo management tool for DevTools.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.1.0
  cli_util: ^0.3.3
  devtools_shared: ^2.18.0
  http: ^0.13.3
  json_annotation: ^4.4.0
  lints: any
  path: ^1.8.0

dependency_overrides:
  devtools_shared:
    path: ../packages/devtools_shared

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
