name: Release Preparation

on:
  pull_request:

jobs:
  check-release-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Check if we have modified release_notes.json 
        id: get-modified-files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export JSON_RELEASE_FILE='packages/devtools_app/lib/src/framework/release_notes/release_notes.json'
          PULL_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          FILES_RESPONSE=$(gh api /repos/flutter/devtools/pulls/$PULL_NUMBER/files)
          CHANGED_FILES=$(echo $FILES_RESPONSE | jq '.[].filename')
          HAS_CHANGED_RELEASE_NOTES=$(echo $FILE_NAMES | jq '. | any(. == env.JSON_RELEASE_FILE)')
          echo "::set-output name=HAS_CHANGED_RELEASE_NOTES::$HAS_CHANGED_RELEASE_NOTES"
      - name: Get PR Labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "THE CHANGED FILES ARE ${{ steps.get-modified-files.outputs.CHANGED_FILES }}"
    
      - name: Add PR Url to Release Notes
        run: 
      - name: Verify release_notes.json integrity
        run: 

          

