name: Release Preparation

on:
  pull_request:

jobs:
  check-release-condition:
    runs-on: ubuntu-latest
    steps:

      - name: Get Pull Request Number
        id: get-pull-request-number
        run: |
          PULL_REQUEST_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "::set-output name=PULL_REQUEST_NUMBER::$PULL_REQUEST_NUMBER"

      - name: Check if we have modified release_notes.json 
        id: get-modified-files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{steps.get-pull-request-number.outputs.PULL_REQUEST_NUMBER}}
        run: |
          export JSON_RELEASE_FILE='packages/devtools_app/lib/src/framework/release_notes/release_notes.json'

          FILES_RESPONSE=$(gh api /repos/flutter/devtools/pulls/$PULL_NUMBER/files)
          echo "FILES_RESPONSE: $FILES_RESPONSE"
          
          HAS_CHANGED_RELEASE_NOTES=$(echo $FILES_RESPONSE | jq '.[].filename | any(. == env.JSON_RELEASE_FILE)')
          echo "HAS_CHANGED_RELEASE_NOTES: $HAS_CHANGED_RELEASE_NOTES"
          echo "::set-output name=HAS_CHANGED_RELEASE_NOTES::$HAS_CHANGED_RELEASE_NOTES"
      - name: Get PR Labels
        id: get-label-exception
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_NUMBER: ${{steps.get-pull-request-number.outputs.PULL_REQUEST_NUMBER}}
        run: |
          PULLS_RESPONSE=$(gh api /repos/flutter/devtools/pulls/$PULL_NUMBER)
          echo $PULLS_RESPONSE
          
          export NOT_USER_FACING_LABEL_ID=123

          HAS_EXCEPTION_LABEL=$(jq '.labels[].id |  any(. == env.NOT_USER_FACING_LABEL_ID)')
          echo "::set-output name=HAS_EXCEPTION_LABEL::$HAS_EXCEPTION_LABEL"
      - name: Test Values 
        env:
          HAS_CHANGED_RELEASE_NOTES: ${{steps.get-modified-files.outputs.HAS_CHANGED_RELEASE_NOTES}}
          HAS_EXCEPTION_LABEL: ${{steps.get-label-exception.outputs.HAS_EXCEPTION_LABEL}}
        run: |
          echo "HAS_CHANGED_RELEASE_NOTES: ${{steps.get-modified-files.outputs.HAS_CHANGED_RELEASE_NOTES}}"

      # - name: Add PR Url to Release Notes
      #   run: 
      # - name: Verify release_notes.json integrity
      #   run: 

          

