name: Release Preparation

on:
  pull_request:

jobs:
  check-release-condition:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Modified Files 
        id: get-modified-files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          JSON_RELEASE_FILE='packages/devtools_app/lib/src/framework/release_notes/release_notes.json'
          PULL_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          FILES_RESPONSE=$(gh api /repos/flutter/devtools/pulls/$PULL_NUMBER/files)
          export CHANGED_FILES=$(echo $FILES_RESPONSE | jq '.[].filename')
          echo "::set-output name=CHANGED_FILES::$CHANGED_FILES"
          # HAS_JSON_RELEASE_FILE=$(echo $FILE_NAMES | jq '. | any(. == env.JSON_RELEASE_FILE)')
      - name: Get PR Labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "THE CHANGED FILES ARE ${{ steps.get-modified-files.outputs.CHANGED_FILES }}"

          

